### ISSUE TITLE
User IDs returned from RIQ API are incorrect?

### ISSUE THREAD

**Issue by zapnap** [relateiq/ruby-sdk#12]
This isn't really specific to the Ruby SDK, but User ID values returned by the APIs seem to always be off by 1... Very strange.

Example:

    user = RIQ::User.new("54610989e4b0e9600160f78e").id => "54610989e4b0e9600160f78f"
    RIQ::User.new(user.id) # raises RIQ::NotFoundError: Object Not Found

Likewise:

    curl 'https://api.salesforceiq.com/v2/users/54610989e4b0e9600160f78e' -X GET -u key:secret -H 'Accept: application/json'
    {"id":"54610989e4b0e9600160f78f","name":"xxxxxx","email":"xxxx@xxxx.com"}

**Comment by Xavdidtheshadow** [comment]
@zapnap Hey, sorry for the delay. Checked with the api team and it turns out we're accidentally surfacing the userId (instead of the profileId, which is what you have in the request. They're separate, but you're interested in the one you already have).

It'll be fixed soon. Correct behavior is the id you send is the same one you'll get back.

**Comment by zapnap** [comment]
Sounds good dude. Thanks for investigating.

**Comment by Xavdidtheshadow** [comment]
will do!

**Comment by Xavdidtheshadow** [comment]
@zapnap Hey, sorry for the slow turnaround but this is now fixed!

```
RIQ.user('5373f91ae4b071e74166a1bc').id == '5373f91ae4b071e74166a1bc' # => true
```

**Comment by zapnap** [comment]
Great thanks!
